services:
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017/hotel_pays_basque
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # ... (services nginx, backend, mongo) ...

  tests:
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/hoteldb
    command: ["pytest", "-v", "tests/"]
    depends_on:
      - backend

volumes:
  mongo-data:
